from transformers import T5Tokenizer, T5ForConditionalGeneration
import torch

class QuestionGeneratorService:
    def __init__(self):
        """
        Initializes the FLAN-T5 Question Generator.
        Loads the flan-t5-small model locally.
        In the future, this will point to 'ml_models/question_generator/' 
        where the fine-tuned model weights are stored.
        """
        try:
            print("Loading FLAN-T5 model for Question Generation...")
            # Using flan-t5-small as the base for immediate testing functionality
            # This will be swapped to the local path of the fine-tuned model later 
            model_name = "google/flan-t5-small"
            self.tokenizer = T5Tokenizer.from_pretrained(model_name)
            self.model = T5ForConditionalGeneration.from_pretrained(model_name)
            print("FLAN-T5 loaded successfully.")
        except Exception as e:
            print(f"Failed to load FLAN-T5 model: {e}")
            self.model = None
            self.tokenizer = None

    def build_prompt(self, skill: str, role: str, difficulty: str = "Medium", question_type: str = "Scenario") -> str:
        """
        Constructs a structured prompt based on the missing skill.
        """
        return f"Generate a {difficulty} level {question_type} interview question for a {role} focusing on {skill}."

    def validate_quality(self, candidates: list, skill: str) -> str:
        """
        Runs quality checks on candidate questions generated by beam search.
        1. Must contain the skill locally or implicitly.
        2. Must be > 10 words.
        3. Should end with a question mark.
        """
        skill_lower = skill.lower()
        
        for candidate in candidates:
            text = candidate.strip()
            # Basic validation rules
            has_length = len(text.split()) > 5 # Adjusted to 5 for t5-small testing
            is_question = text.endswith('?')
            
            # Simple heuristic check, preferring questions that heavily feature the skill
            if has_length and is_question:
                return text
                
        # If all fail, return the best effort (first candidate) or trigger Fallback Retriever
        # For now, return the top candidate.
        return candidates[0] if candidates else "Could you explain your experience with " + skill + "?"

    def generate_question(self, skill: str, role: str) -> dict:
        """
        End-to-end question generation via inference.
        """
        if not self.model or not self.tokenizer:
            return {"error": "Model is not loaded properly."}

        prompt = self.build_prompt(skill, role)

        # 1. Tokenize prompt
        input_ids = self.tokenizer(prompt, return_tensors="pt").input_ids

        # 2. Run Forward Pass with Beam Search
        try:
            outputs = self.model.generate(
                input_ids,
                max_length=100,
                num_beams=5,             # Try 5 paths, pick the best
                num_return_sequences=5,  # Return 5 candidates for quality check
                temperature=0.7,         # Controls creativity
                no_repeat_ngram_size=2,  # Avoids repeated phrases inside the question
                do_sample=True           # Required for temperature to take effect
            )
            
            # 3. Decode candidates from tokens back to text
            candidates = [self.tokenizer.decode(output, skip_special_tokens=True) for output in outputs]
            
            # 4. Quality Check
            best_question = self.validate_quality(candidates, skill)

            return {
                "status": "success",
                "skill_targeted": skill,
                "role_targeted": role,
                "prompt_used": prompt,
                "generated_question": best_question,
                "candidates": candidates
            }
            
        except Exception as e:
            return {"error": f"Error during generation: {str(e)}"}
